engine:
  pet_tasks_time: 300
  sadness_index: 1
  time_of_last_check: '2024-05-23T12:27:20.422786'
food:
  hunger_index: 1
  list:
    apple:
      feed_index: 3
      name: Apple
    banana:
      feed_index: 1
      name: Banana
    potato:
      feed_index: 2
      name: Potato
  zero_health_index: 10
games:
  list:
    1:
      name: Тест1
      play_index: 1
    2:
      name: Тест2
      play_index: 2
imgs:
  font_path: fonts/Aqum.ttf
  font_size: 24
  path_panels_folder: imgs/panels/
  path_pets_folder: imgs/pets/
  path_rooms_folder: imgs/rooms/
play:
  break_play_index: 5
  play_again_index: 15
  play_index: 5
  zero_health_index: 1
secret:
  owner_id: OWNER_ID
  telegram_token: 7194321199:AAEU5khI7cPWhiqITs5XK4CvI0S3V46hsr0
sleep:
  break_sleep_index: 5
  health_sleep_index: 1
  min_sleep_index: 75
  sleep_down_index: 1
  sleep_index: 3
  zero_health_index: 3
