engine:
  hunger_index: 1
  pet_tasks_time: 300
  sadness_index: 1
  time_of_last_check: '2024-05-20T04:04:04.763926'
food:
  list:
    1:
      feed_index: null
      name: null
    2:
      feed_index: null
      name: null
    3:
      feed_index: null
      name: null
play:
  break_play_index: 5
  play_again_index: 15
  play_index: 5
secret:
  owner_id: OWNER_ID
  telegram_token: 7194321199:AAEU5khI7cPWhiqITs5XK4CvI0S3V46hsr0
sleep:
  break_sleep_index: 5
  health_sleep_index: 1
  sleep_index: 1
