collect_food:
  chance: 0.9
  max_collect_food: 50
engine:
  hatching_timer: 3
  health_index: 0
  health_min_value: 30
  notification_time: 30
  pet_tasks_time: 300
  sadness_index: 1
  time_of_last_check: '2024-05-26T16:03:43.017070'
food:
  collect_index: 2
  hunger_index: 1
  min_value: 30
  zero_health_index: -10
games:
  list:
    1:
      name: ğŸ’ƒ | Ğ¢Ğ°Ğ½Ñ†Ñ‹
      play_index: 3
      sleep: 3
    2:
      name: ğŸŒ€ | Ğ›Ğ°Ğ±Ğ¸Ñ€Ğ¸Ğ½Ñ‚
      play_index: 2
      sleep: 1
    3:
      name: ğŸ¨ | Ğ Ğ¸ÑĞ¾Ğ²Ğ°Ğ½Ğ¸Ğµ
      play_index: 1
      sleep: 1
    4:
      name: ğŸŠ | ĞŸĞ»Ğ°Ğ²Ğ°Ğ½ÑŒĞµ
      play_index: 2
      sleep: 1
    5:
      name: ğŸ² | ĞšÑƒĞ±Ğ¸Ğº Ñ€ÑƒĞ±Ğ¸ĞºĞ°
      play_index: 4
      sleep: 1
    6:
      name: ğŸµ | ĞœÑƒĞ·Ñ‹ĞºĞ°
      play_index: 2
      sleep: 1
    7:
      name: ğŸï¸ | Ğ“Ğ¾Ğ½ĞºĞ¸
      play_index: 4
      sleep: 5
    8:
      name: âš½ | Ğ˜Ğ³Ñ€Ğ° Ñ Ğ¼ÑÑ‡Ğ¾Ğ¼
      play_index: 2
      sleep: 5
imgs:
  font_path: fonts/Aqum.ttf
  font_size_eggs: 50
  font_size_info: 24
  path_backgrounds_folder: imgs/backgrounds/
  path_eggs_folder: imgs/eggs/
  path_panels_folder: imgs/panels/
  path_pets_folder: imgs/pets/
  path_rooms_folder: imgs/rooms/
journey:
  event_in_journey: 0.3
  min_health: 15
  replace_to: '##'
  words_to_replace: 4
level:
  collecting: 10
  experience: 100
  level_up_for_activity_by_time: 1800
  max_education_buff: 40
  playing: 15
  sleeping: 5
  traveling: 20
play:
  break_play_index: 5
  min_value: 30
  play_again_index: 15
  play_index: 5
  zero_health_index: -10
secret:
  owner_id: OWNER_ID
  telegram_token: 7194321199:AAGTSs5duuyO-pGNq_Gpbq1IU8_AWZffmnk
sleep:
  break_sleep_index: 5
  health_sleep_index: 1
  min_sleep_index: 75
  min_value: 30
  sleep_down_index: 1
  sleep_index: 3
  zero_health_index: -12
