collect_food:
  chance: 1.0
  max_collect_food: 50
engine:
  hatching_timer: 600
  pet_tasks_time: 300
  sadness_index: 1
  time_of_last_check: '2024-05-24T04:22:11.680861'
food:
  collect_index: 2
  hunger_index: 1
  list:
    algae:
      can_find: true
      chance: 0.3
      feed_index: 3
      name: üåø –í–æ–¥–æ—Ä–æ—Å–ª–∏
    apple:
      can_find: true
      chance: 0.3
      feed_index: 3
      name: üçé –Ø–±–ª–æ–∫–æ
    berry:
      can_find: true
      chance: 0.5
      feed_index: 1
      name: üçá –Ø–≥–æ–¥—ã
    bread:
      can_find: true
      chance: 0.2
      feed_index: 4
      name: üçû –•–ª–µ–±
    carrot:
      can_find: true
      chance: 0.5
      feed_index: 2
      name: ü•ï –ú–æ—Ä–∫–æ–≤—å
    fish:
      can_find: false
      feed_index: 9
      name: üêü –ú–µ–ª–∫–∞—è —Ä—ã–±–∞
    lettuce:
      can_find: true
      chance: 0.2
      feed_index: 3
      name: ü•¨ –°–∞–ª–∞—Ç
    turtle_food:
      can_find: false
      feed_index: 10
      name: ü•´ –ö–æ—Ä–º –¥–ª—è —á–µ—Ä–µ–ø–∞—à–µ–∫
  zero_health_index: 10
games:
  list:
    1:
      name: –¢–µ—Å—Ç1
      play_index: 1
    2:
      name: –¢–µ—Å—Ç2
      play_index: 2
imgs:
  font_path: fonts/Aqum.ttf
  font_size_eggs: 50
  font_size_info: 24
  path_backgrounds_folder: imgs/backgrounds/
  path_eggs_folder: imgs/eggs/
  path_panels_folder: imgs/panels/
  path_pets_folder: imgs/pets/
  path_rooms_folder: imgs/rooms/
play:
  break_play_index: 5
  play_again_index: 15
  play_index: 5
  zero_health_index: 1
secret:
  owner_id: OWNER_ID
  telegram_token: 7194321199:AAEU5khI7cPWhiqITs5XK4CvI0S3V46hsr0
sleep:
  break_sleep_index: 5
  health_sleep_index: 1
  min_sleep_index: 75
  sleep_down_index: 1
  sleep_index: 3
  zero_health_index: 3
